#!/usr/bin/env python

#Script to use the Fisher Scientific PPS4102 Top Pan balance in ROS
import sys
import rospy
from peristaltic_dispenser_driver.DispenserDriverROS import DispDriverROS
            
if __name__ == "__main__": #Object oriented initialization for ROS
    if len(sys.argv) > 1:
        kern_serial_port = sys.argv[1]
    else:
        kern_serial_port = '/dev/ttyUSB0'
        rospy.logerr('No input serial port for Kern balance is provided. The default serial port (ttyUSB0) is used')
    rospy.init_node("dispenser_driver", anonymous=True) #initialize rospy node
    dispenser_ROS = DispDriverROS(kern_serial_port) #Create instance of ROS Wrapper
    rospy.on_shutdown(dispenser_ROS.reset) #Turn off scale when driver is turned off
    rospy.loginfo("Dispenser driver started")
    rospy.spin()
